// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Le schema engine de la CLI Prisma (migrate dev/deploy, db push, studio...) ne sait pas
// se connecter à un datasource libsql:// : ça ne passe que par un adaptateur driver, qui
// n'existe qu'au runtime du client (voir lib/prisma.ts). La CLI reste donc toujours sur le
// fichier SQLite local ; pousser le schéma vers Turso se fait via
// scripts/push-schema-to-turso.mjs (npm run db:push-to-turso), pas via cette config.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.mjs",
  },
  datasource: {
    url: "file:./dev.db",
  },
});
